# Generated by Django 4.1.3 on 2022-11-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoners', models.CharField(max_length=255)),
                ('game', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('champion', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('d_spell', models.CharField(max_length=255)),
                ('f_spell', models.CharField(max_length=255)),
                ('main_rune', models.CharField(max_length=255)),
                ('sub_rune', models.CharField(max_length=255)),
                ('items', models.TextField()),
                ('kill', models.IntegerField()),
                ('death', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('p_kill', models.CharField(max_length=255)),
                ('pinkward', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('cs_per_min', models.IntegerField()),
                ('average_tier', models.CharField(max_length=255)),
                ('team_champs', models.TextField()),
                ('team', models.TextField()),
                ('enemy_champs', models.TextField()),
                ('enemy', models.TextField()),
                ('side', models.CharField(max_length=255)),
            ],
        ),
    ]
