# Generated by Django 4.1.3 on 2022-11-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='data',
            table='data',
        ),
    ]
