# Generated by Django 4.1.3 on 2022-11-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project3', '0002_alter_data_id_alter_data_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='champion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='d_spell',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='f_spell',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='main_rune',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='sub_rune',
            field=models.TextField(),
        ),
    ]
